version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpw
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3311:3306"
    restart: always
    
  web:
    image: php-apache:1.0
    container_name: docker-php
    ports:
      - "8090:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql